package br.com.energymng.ocppgateway;

public enum OcppAction {
    BOOT_NOTIFICATION,
    HEARTBEAT,
    AUTHORIZE,
    START_TRANSACTION,
    STOP_TRANSACTION,
    STATUS_NOTIFICATION,
    METER_VALUES,
    CHANGE_CONFIGURATION,
    RESET,
    REMOTE_START_TRANSACTION,
    REMOTE_STOP_TRANSACTION
}
